version = 1

test_patterns = ["**/__tests__/**", "**/*.test.ts", "**/*.spec.ts"]

exclude_patterns = ["node_modules/**", "dist/**", "build/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.options]
  scan_type = "ts"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

