name: CI

on:
  push:
    branches:
      - main
      - "feature/**" # Runs on any branch starting with "feature/"
  pull_request:
    branches:
      - main
      - "feature/**" # Runs on PRs targeting branches starting with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build
